services:
  backend:
    build:
      context: ./springboot
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Front-Back_Project?useSSL=false&charset=utf8mb4
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql123
    volumes:
      - file_storage:/app/files  # 将容器内的 /app/files 映射到持久化卷
      # 其他配置不变...
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./vue
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://backend:9090/api
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: Front-Back_Project
      MYSQL_ROOT_PASSWORD: mysql123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # 避免與本地 MySQL 衝突
    networks:
      - app-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  file_storage:

networks:
  app-network:
    driver: bridge